name: medfast_go
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+5

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4
  flutter_typeahead: ^3.1.1
  shared_preferences: ^2.0.9
  intl_phone_number_input: ^0.7.3+1
  cupertino_icons: ^1.0.2
  geolocator: ^8.0.0
  http: ^0.13.3
  permission_handler: ^8.0.1
  intl: ^0.17.0
  sqflite: ^2.0.0
  path_provider_foundation: ^2.3.1
  qr_code_scanner: ^1.0.1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/Medrxlogo.png
    - lib/assets/Successmark.png
    - lib/assets/medicine.png
    - lib/assets/barcode_icon.png
    - lib/assets/no_barcode_icon.png
    - lib/assets/Posimage.png
    - lib/assets/Financial Insights.png
    - lib/assets/bar-code.png
    - lib/assets/pharmacy-store.png
    - lib/assets/barcode_icon.png
    - lib/assets/barcode.png
    - lib/assets/cash.png
    - lib/assets/MobilePay.jfif
    - lib/assets/no-barcode.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
