// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARBin0TuW8TksfMhtC41GFJMsY759-9Lw',
    appId: '1:276228943497:web:56b3874f46fc6feefca058',
    messagingSenderId: '276228943497',
    projectId: 'medfastgo-d96a2',
    authDomain: 'medfastgo-d96a2.firebaseapp.com',
    storageBucket: 'medfastgo-d96a2.appspot.com',
    measurementId: 'G-R1SGBZ1MT4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmQSohHOTC0AVA4JsM7KUXDB5R6R4MxF8',
    appId: '1:276228943497:android:8e8fccd1b59c5808fca058',
    messagingSenderId: '276228943497',
    projectId: 'medfastgo-d96a2',
    storageBucket: 'medfastgo-d96a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKenLYQgqCIhpIEJ_OxqqXoc80vmHkdx8',
    appId: '1:276228943497:ios:f97b510a069358c0fca058',
    messagingSenderId: '276228943497',
    projectId: 'medfastgo-d96a2',
    storageBucket: 'medfastgo-d96a2.appspot.com',
    iosBundleId: 'com.example.medfastGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKenLYQgqCIhpIEJ_OxqqXoc80vmHkdx8',
    appId: '1:276228943497:ios:f97b510a069358c0fca058',
    messagingSenderId: '276228943497',
    projectId: 'medfastgo-d96a2',
    storageBucket: 'medfastgo-d96a2.appspot.com',
    iosBundleId: 'com.example.medfastGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARBin0TuW8TksfMhtC41GFJMsY759-9Lw',
    appId: '1:276228943497:web:30f33ead05ccdb8bfca058',
    messagingSenderId: '276228943497',
    projectId: 'medfastgo-d96a2',
    authDomain: 'medfastgo-d96a2.firebaseapp.com',
    storageBucket: 'medfastgo-d96a2.appspot.com',
    measurementId: 'G-2E84L94F1F',
  );

}